# Generated by Django 5.1 on 2024-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('insecticidas', 'Insecticidas'), ('antibioticos', 'Antibióticos'), ('vitaminicos', 'Vitaminicos'), ('antiinflamatorios', 'Antiinflamatorios'), ('desparasitantes', 'Desparasitantes')], default='insecticidas', max_length=20),
        ),
    ]
